# Use this section to suppress warnings generated by your code:
def warn(*args, **kwargs):
    pass
import warnings
warnings.warn = warn
warnings.filterwarnings('ignore')

from langchain_community.llms import Ollama # Import Ollama LLM
from langchain.agents import AgentType
from langchain_community.utilities.sql_database import SQLDatabase
from langchain_community.agent_toolkits import create_sql_agent
import argparse
import os # For environment variables

# --- Ollama LLM Setup ---
# Ensure Ollama is running and has the model downloaded (e.g., 'phi3:mini')
# You can specify the model to use from Ollama
# For example, llm = Ollama(model="llama2") or llm = Ollama(model="phi3:mini")
llm = Ollama(model="mistral:7b-instruct", temperature=0.2) # Using phi3:mini as a lightweight example

# --- MySQL Database Connector ---
# IMPORTANT: Replace with your MySQL details
# You can get these from your MySQL setup, usually:
# mysql_username: root
# mysql_password: The password you set during MySQL installation
# mysql_host: localhost (since it's on your local machine)
# mysql_port: 3306 (default MySQL port)
# database_name: Chinook (the database you created)

mysql_username = 'root'
mysql_password = 'root' # <<< REPLACE THIS
mysql_host = 'localhost'
mysql_port = '3306'
database_name = 'Chinook'

mysql_uri = f'mysql+mysqlconnector://{mysql_username}:{mysql_password}@{mysql_host}:{mysql_port}/{database_name}'
db = SQLDatabase.from_uri(mysql_uri)

# --- Create SQL Agent ---
agent_executor = create_sql_agent(
    llm=llm,
    db=db,
    verbose=True,
    handle_parsing_errors=True,
    agent_type=AgentType.ZERO_SHOT_REACT_DESCRIPTION
)

# --- Command Line Argument for Prompt ---
"""
parser = argparse.ArgumentParser()
parser.add_argument("--prompt", type=str, help="The prompt to send to the SQL agent")
args = parser.parse_args()
"""
# Use the prompt from command line argument
if args.prompt:
    try:
        agent_executor.invoke({"input": args.prompt})
    except Exception as e:
        print(f"An error occurred: {e}")
        print("Please ensure your MySQL server is running and accessible, and Ollama is running with the specified model.")
else:
    print("Please provide a prompt using --prompt argument")